/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing ArtifactCollectionSort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArtifactCollectionSortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ArtifactCollectionSort
        //private ArtifactCollectionSort instance;

        public ArtifactCollectionSortTests()
        {
            // TODO uncomment below to create an instance of ArtifactCollectionSort
            //instance = new ArtifactCollectionSort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ArtifactCollectionSort
        /// </summary>
        [Fact]
        public void ArtifactCollectionSortInstanceTest()
        {
            // TODO uncomment below to test "IsType" ArtifactCollectionSort
            //Assert.IsType<ArtifactCollectionSort>(instance);
        }
    }
}
