/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing BlockSchemaFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockSchemaFilterTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockSchemaFilter
        //private BlockSchemaFilter instance;

        public BlockSchemaFilterTests()
        {
            // TODO uncomment below to create an instance of BlockSchemaFilter
            //instance = new BlockSchemaFilter();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockSchemaFilter
        /// </summary>
        [Fact]
        public void BlockSchemaFilterInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockSchemaFilter
            //Assert.IsType<BlockSchemaFilter>(instance);
        }

        /// <summary>
        /// Test the property 'FilterOperator'
        /// </summary>
        [Fact]
        public void FilterOperatorTest()
        {
            // TODO unit test for the property 'FilterOperator'
        }

        /// <summary>
        /// Test the property 'BlockTypeId'
        /// </summary>
        [Fact]
        public void BlockTypeIdTest()
        {
            // TODO unit test for the property 'BlockTypeId'
        }

        /// <summary>
        /// Test the property 'BlockCapabilities'
        /// </summary>
        [Fact]
        public void BlockCapabilitiesTest()
        {
            // TODO unit test for the property 'BlockCapabilities'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
