/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing BlockDocumentUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockDocumentUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockDocumentUpdate
        //private BlockDocumentUpdate instance;

        public BlockDocumentUpdateTests()
        {
            // TODO uncomment below to create an instance of BlockDocumentUpdate
            //instance = new BlockDocumentUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockDocumentUpdate
        /// </summary>
        [Fact]
        public void BlockDocumentUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockDocumentUpdate
            //Assert.IsType<BlockDocumentUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'BlockSchemaId'
        /// </summary>
        [Fact]
        public void BlockSchemaIdTest()
        {
            // TODO unit test for the property 'BlockSchemaId'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'MergeExistingData'
        /// </summary>
        [Fact]
        public void MergeExistingDataTest()
        {
            // TODO unit test for the property 'MergeExistingData'
        }
    }
}
