/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing BlockDocumentFilterBlockTypeId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockDocumentFilterBlockTypeIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockDocumentFilterBlockTypeId
        //private BlockDocumentFilterBlockTypeId instance;

        public BlockDocumentFilterBlockTypeIdTests()
        {
            // TODO uncomment below to create an instance of BlockDocumentFilterBlockTypeId
            //instance = new BlockDocumentFilterBlockTypeId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockDocumentFilterBlockTypeId
        /// </summary>
        [Fact]
        public void BlockDocumentFilterBlockTypeIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockDocumentFilterBlockTypeId
            //Assert.IsType<BlockDocumentFilterBlockTypeId>(instance);
        }

        /// <summary>
        /// Test the property 'Any'
        /// </summary>
        [Fact]
        public void AnyTest()
        {
            // TODO unit test for the property 'Any'
        }
    }
}
