/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing BlockTypeFilterSlug
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BlockTypeFilterSlugTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BlockTypeFilterSlug
        //private BlockTypeFilterSlug instance;

        public BlockTypeFilterSlugTests()
        {
            // TODO uncomment below to create an instance of BlockTypeFilterSlug
            //instance = new BlockTypeFilterSlug();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BlockTypeFilterSlug
        /// </summary>
        [Fact]
        public void BlockTypeFilterSlugInstanceTest()
        {
            // TODO uncomment below to test "IsType" BlockTypeFilterSlug
            //Assert.IsType<BlockTypeFilterSlug>(instance);
        }

        /// <summary>
        /// Test the property 'Any'
        /// </summary>
        [Fact]
        public void AnyTest()
        {
            // TODO unit test for the property 'Any'
        }
    }
}
