/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing ConcurrencyLimitV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConcurrencyLimitV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConcurrencyLimitV2
        //private ConcurrencyLimitV2 instance;

        public ConcurrencyLimitV2Tests()
        {
            // TODO uncomment below to create an instance of ConcurrencyLimitV2
            //instance = new ConcurrencyLimitV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConcurrencyLimitV2
        /// </summary>
        [Fact]
        public void ConcurrencyLimitV2InstanceTest()
        {
            // TODO uncomment below to test "IsType" ConcurrencyLimitV2
            //Assert.IsType<ConcurrencyLimitV2>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }

        /// <summary>
        /// Test the property 'ActiveSlots'
        /// </summary>
        [Fact]
        public void ActiveSlotsTest()
        {
            // TODO unit test for the property 'ActiveSlots'
        }

        /// <summary>
        /// Test the property 'DeniedSlots'
        /// </summary>
        [Fact]
        public void DeniedSlotsTest()
        {
            // TODO unit test for the property 'DeniedSlots'
        }

        /// <summary>
        /// Test the property 'SlotDecayPerSecond'
        /// </summary>
        [Fact]
        public void SlotDecayPerSecondTest()
        {
            // TODO unit test for the property 'SlotDecayPerSecond'
        }

        /// <summary>
        /// Test the property 'AvgSlotOccupancySeconds'
        /// </summary>
        [Fact]
        public void AvgSlotOccupancySecondsTest()
        {
            // TODO unit test for the property 'AvgSlotOccupancySeconds'
        }
    }
}
