/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing FlowRunFilterState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlowRunFilterStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlowRunFilterState
        //private FlowRunFilterState instance;

        public FlowRunFilterStateTests()
        {
            // TODO uncomment below to create an instance of FlowRunFilterState
            //instance = new FlowRunFilterState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlowRunFilterState
        /// </summary>
        [Fact]
        public void FlowRunFilterStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlowRunFilterState
            //Assert.IsType<FlowRunFilterState>(instance);
        }

        /// <summary>
        /// Test the property 'FilterOperator'
        /// </summary>
        [Fact]
        public void FilterOperatorTest()
        {
            // TODO unit test for the property 'FilterOperator'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
