/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing FlowRunFilterId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlowRunFilterIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlowRunFilterId
        //private FlowRunFilterId instance;

        public FlowRunFilterIdTests()
        {
            // TODO uncomment below to create an instance of FlowRunFilterId
            //instance = new FlowRunFilterId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlowRunFilterId
        /// </summary>
        [Fact]
        public void FlowRunFilterIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlowRunFilterId
            //Assert.IsType<FlowRunFilterId>(instance);
        }

        /// <summary>
        /// Test the property 'Any'
        /// </summary>
        [Fact]
        public void AnyTest()
        {
            // TODO unit test for the property 'Any'
        }

        /// <summary>
        /// Test the property 'NotAny'
        /// </summary>
        [Fact]
        public void NotAnyTest()
        {
            // TODO unit test for the property 'NotAny'
        }
    }
}
