/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing FlowRunFilterExpectedStartTime
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlowRunFilterExpectedStartTimeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlowRunFilterExpectedStartTime
        //private FlowRunFilterExpectedStartTime instance;

        public FlowRunFilterExpectedStartTimeTests()
        {
            // TODO uncomment below to create an instance of FlowRunFilterExpectedStartTime
            //instance = new FlowRunFilterExpectedStartTime();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlowRunFilterExpectedStartTime
        /// </summary>
        [Fact]
        public void FlowRunFilterExpectedStartTimeInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlowRunFilterExpectedStartTime
            //Assert.IsType<FlowRunFilterExpectedStartTime>(instance);
        }

        /// <summary>
        /// Test the property 'Before'
        /// </summary>
        [Fact]
        public void BeforeTest()
        {
            // TODO unit test for the property 'Before'
        }

        /// <summary>
        /// Test the property 'After'
        /// </summary>
        [Fact]
        public void AfterTest()
        {
            // TODO unit test for the property 'After'
        }
    }
}
