/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing FlowRunNotificationPolicyFilterIsActive
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlowRunNotificationPolicyFilterIsActiveTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlowRunNotificationPolicyFilterIsActive
        //private FlowRunNotificationPolicyFilterIsActive instance;

        public FlowRunNotificationPolicyFilterIsActiveTests()
        {
            // TODO uncomment below to create an instance of FlowRunNotificationPolicyFilterIsActive
            //instance = new FlowRunNotificationPolicyFilterIsActive();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlowRunNotificationPolicyFilterIsActive
        /// </summary>
        [Fact]
        public void FlowRunNotificationPolicyFilterIsActiveInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlowRunNotificationPolicyFilterIsActive
            //Assert.IsType<FlowRunNotificationPolicyFilterIsActive>(instance);
        }

        /// <summary>
        /// Test the property 'Eq'
        /// </summary>
        [Fact]
        public void EqTest()
        {
            // TODO unit test for the property 'Eq'
        }
    }
}
