/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing FlowCreate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlowCreateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlowCreate
        //private FlowCreate instance;

        public FlowCreateTests()
        {
            // TODO uncomment below to create an instance of FlowCreate
            //instance = new FlowCreate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlowCreate
        /// </summary>
        [Fact]
        public void FlowCreateInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlowCreate
            //Assert.IsType<FlowCreate>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
