/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing FlowRunUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FlowRunUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FlowRunUpdate
        //private FlowRunUpdate instance;

        public FlowRunUpdateTests()
        {
            // TODO uncomment below to create an instance of FlowRunUpdate
            //instance = new FlowRunUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlowRunUpdate
        /// </summary>
        [Fact]
        public void FlowRunUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" FlowRunUpdate
            //Assert.IsType<FlowRunUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'FlowVersion'
        /// </summary>
        [Fact]
        public void FlowVersionTest()
        {
            // TODO unit test for the property 'FlowVersion'
        }

        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Fact]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

        /// <summary>
        /// Test the property 'EmpiricalPolicy'
        /// </summary>
        [Fact]
        public void EmpiricalPolicyTest()
        {
            // TODO unit test for the property 'EmpiricalPolicy'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'InfrastructurePid'
        /// </summary>
        [Fact]
        public void InfrastructurePidTest()
        {
            // TODO unit test for the property 'InfrastructurePid'
        }
    }
}
