/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing LogFilterTaskRunId
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogFilterTaskRunIdTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogFilterTaskRunId
        //private LogFilterTaskRunId instance;

        public LogFilterTaskRunIdTests()
        {
            // TODO uncomment below to create an instance of LogFilterTaskRunId
            //instance = new LogFilterTaskRunId();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogFilterTaskRunId
        /// </summary>
        [Fact]
        public void LogFilterTaskRunIdInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogFilterTaskRunId
            //Assert.IsType<LogFilterTaskRunId>(instance);
        }

        /// <summary>
        /// Test the property 'Any'
        /// </summary>
        [Fact]
        public void AnyTest()
        {
            // TODO unit test for the property 'Any'
        }
    }
}
