/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing PrefectFlowDefaultRetryDelaySeconds
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PrefectFlowDefaultRetryDelaySecondsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PrefectFlowDefaultRetryDelaySeconds
        //private PrefectFlowDefaultRetryDelaySeconds instance;

        public PrefectFlowDefaultRetryDelaySecondsTests()
        {
            // TODO uncomment below to create an instance of PrefectFlowDefaultRetryDelaySeconds
            //instance = new PrefectFlowDefaultRetryDelaySeconds();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PrefectFlowDefaultRetryDelaySeconds
        /// </summary>
        [Fact]
        public void PrefectFlowDefaultRetryDelaySecondsInstanceTest()
        {
            // TODO uncomment below to test "IsType" PrefectFlowDefaultRetryDelaySeconds
            //Assert.IsType<PrefectFlowDefaultRetryDelaySeconds>(instance);
        }
    }
}
