/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing ReadWorkQueuesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReadWorkQueuesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReadWorkQueuesRequest
        //private ReadWorkQueuesRequest instance;

        public ReadWorkQueuesRequestTests()
        {
            // TODO uncomment below to create an instance of ReadWorkQueuesRequest
            //instance = new ReadWorkQueuesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReadWorkQueuesRequest
        /// </summary>
        [Fact]
        public void ReadWorkQueuesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReadWorkQueuesRequest
            //Assert.IsType<ReadWorkQueuesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

        /// <summary>
        /// Test the property 'WorkQueues'
        /// </summary>
        [Fact]
        public void WorkQueuesTest()
        {
            // TODO unit test for the property 'WorkQueues'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
    }
}
