/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing ReadWorkQueueRunsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReadWorkQueueRunsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReadWorkQueueRunsRequest
        //private ReadWorkQueueRunsRequest instance;

        public ReadWorkQueueRunsRequestTests()
        {
            // TODO uncomment below to create an instance of ReadWorkQueueRunsRequest
            //instance = new ReadWorkQueueRunsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReadWorkQueueRunsRequest
        /// </summary>
        [Fact]
        public void ReadWorkQueueRunsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReadWorkQueueRunsRequest
            //Assert.IsType<ReadWorkQueueRunsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'ScheduledBefore'
        /// </summary>
        [Fact]
        public void ScheduledBeforeTest()
        {
            // TODO unit test for the property 'ScheduledBefore'
        }

        /// <summary>
        /// Test the property 'AgentId'
        /// </summary>
        [Fact]
        public void AgentIdTest()
        {
            // TODO unit test for the property 'AgentId'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
    }
}
