/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing ReadTaskRunsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ReadTaskRunsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ReadTaskRunsRequest
        //private ReadTaskRunsRequest instance;

        public ReadTaskRunsRequestTests()
        {
            // TODO uncomment below to create an instance of ReadTaskRunsRequest
            //instance = new ReadTaskRunsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReadTaskRunsRequest
        /// </summary>
        [Fact]
        public void ReadTaskRunsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ReadTaskRunsRequest
            //Assert.IsType<ReadTaskRunsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Sort'
        /// </summary>
        [Fact]
        public void SortTest()
        {
            // TODO unit test for the property 'Sort'
        }

        /// <summary>
        /// Test the property 'Offset'
        /// </summary>
        [Fact]
        public void OffsetTest()
        {
            // TODO unit test for the property 'Offset'
        }

        /// <summary>
        /// Test the property 'Flows'
        /// </summary>
        [Fact]
        public void FlowsTest()
        {
            // TODO unit test for the property 'Flows'
        }

        /// <summary>
        /// Test the property 'FlowRuns'
        /// </summary>
        [Fact]
        public void FlowRunsTest()
        {
            // TODO unit test for the property 'FlowRuns'
        }

        /// <summary>
        /// Test the property 'TaskRuns'
        /// </summary>
        [Fact]
        public void TaskRunsTest()
        {
            // TODO unit test for the property 'TaskRuns'
        }

        /// <summary>
        /// Test the property 'Deployments'
        /// </summary>
        [Fact]
        public void DeploymentsTest()
        {
            // TODO unit test for the property 'Deployments'
        }

        /// <summary>
        /// Test the property 'Limit'
        /// </summary>
        [Fact]
        public void LimitTest()
        {
            // TODO unit test for the property 'Limit'
        }
    }
}
