/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing SetTaskRunStateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetTaskRunStateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SetTaskRunStateRequest
        //private SetTaskRunStateRequest instance;

        public SetTaskRunStateRequestTests()
        {
            // TODO uncomment below to create an instance of SetTaskRunStateRequest
            //instance = new SetTaskRunStateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SetTaskRunStateRequest
        /// </summary>
        [Fact]
        public void SetTaskRunStateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SetTaskRunStateRequest
            //Assert.IsType<SetTaskRunStateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Force'
        /// </summary>
        [Fact]
        public void ForceTest()
        {
            // TODO unit test for the property 'Force'
        }
    }
}
