/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing SimpleFlowRun
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SimpleFlowRunTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SimpleFlowRun
        //private SimpleFlowRun instance;

        public SimpleFlowRunTests()
        {
            // TODO uncomment below to create an instance of SimpleFlowRun
            //instance = new SimpleFlowRun();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SimpleFlowRun
        /// </summary>
        [Fact]
        public void SimpleFlowRunInstanceTest()
        {
            // TODO uncomment below to test "IsType" SimpleFlowRun
            //Assert.IsType<SimpleFlowRun>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'StateType'
        /// </summary>
        [Fact]
        public void StateTypeTest()
        {
            // TODO unit test for the property 'StateType'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Lateness'
        /// </summary>
        [Fact]
        public void LatenessTest()
        {
            // TODO unit test for the property 'Lateness'
        }
    }
}
