/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing StateRejectDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StateRejectDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StateRejectDetails
        //private StateRejectDetails instance;

        public StateRejectDetailsTests()
        {
            // TODO uncomment below to create an instance of StateRejectDetails
            //instance = new StateRejectDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StateRejectDetails
        /// </summary>
        [Fact]
        public void StateRejectDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" StateRejectDetails
            //Assert.IsType<StateRejectDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
    }
}
