/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing UpdatedBy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdatedByTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdatedBy
        //private UpdatedBy instance;

        public UpdatedByTests()
        {
            // TODO uncomment below to create an instance of UpdatedBy
            //instance = new UpdatedBy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdatedBy
        /// </summary>
        [Fact]
        public void UpdatedByInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdatedBy
            //Assert.IsType<UpdatedBy>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'DisplayValue'
        /// </summary>
        [Fact]
        public void DisplayValueTest()
        {
            // TODO unit test for the property 'DisplayValue'
        }
    }
}
