/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing ValidationError
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ValidationErrorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ValidationError
        //private ValidationError instance;

        public ValidationErrorTests()
        {
            // TODO uncomment below to create an instance of ValidationError
            //instance = new ValidationError();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ValidationError
        /// </summary>
        [Fact]
        public void ValidationErrorInstanceTest()
        {
            // TODO uncomment below to test "IsType" ValidationError
            //Assert.IsType<ValidationError>(instance);
        }

        /// <summary>
        /// Test the property 'Loc'
        /// </summary>
        [Fact]
        public void LocTest()
        {
            // TODO unit test for the property 'Loc'
        }

        /// <summary>
        /// Test the property 'Msg'
        /// </summary>
        [Fact]
        public void MsgTest()
        {
            // TODO unit test for the property 'Msg'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
