/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing VariableFilterTags
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VariableFilterTagsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VariableFilterTags
        //private VariableFilterTags instance;

        public VariableFilterTagsTests()
        {
            // TODO uncomment below to create an instance of VariableFilterTags
            //instance = new VariableFilterTags();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VariableFilterTags
        /// </summary>
        [Fact]
        public void VariableFilterTagsInstanceTest()
        {
            // TODO uncomment below to test "IsType" VariableFilterTags
            //Assert.IsType<VariableFilterTags>(instance);
        }

        /// <summary>
        /// Test the property 'FilterOperator'
        /// </summary>
        [Fact]
        public void FilterOperatorTest()
        {
            // TODO unit test for the property 'FilterOperator'
        }

        /// <summary>
        /// Test the property 'All'
        /// </summary>
        [Fact]
        public void AllTest()
        {
            // TODO unit test for the property 'All'
        }

        /// <summary>
        /// Test the property 'IsNull'
        /// </summary>
        [Fact]
        public void IsNullTest()
        {
            // TODO unit test for the property 'IsNull'
        }
    }
}
