/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing WorkQueueHealthPolicy
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkQueueHealthPolicyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkQueueHealthPolicy
        //private WorkQueueHealthPolicy instance;

        public WorkQueueHealthPolicyTests()
        {
            // TODO uncomment below to create an instance of WorkQueueHealthPolicy
            //instance = new WorkQueueHealthPolicy();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkQueueHealthPolicy
        /// </summary>
        [Fact]
        public void WorkQueueHealthPolicyInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkQueueHealthPolicy
            //Assert.IsType<WorkQueueHealthPolicy>(instance);
        }

        /// <summary>
        /// Test the property 'MaximumLateRuns'
        /// </summary>
        [Fact]
        public void MaximumLateRunsTest()
        {
            // TODO unit test for the property 'MaximumLateRuns'
        }

        /// <summary>
        /// Test the property 'MaximumSecondsSinceLastPolled'
        /// </summary>
        [Fact]
        public void MaximumSecondsSinceLastPolledTest()
        {
            // TODO unit test for the property 'MaximumSecondsSinceLastPolled'
        }
    }
}
