/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing WorkQueue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkQueueTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkQueue
        //private WorkQueue instance;

        public WorkQueueTests()
        {
            // TODO uncomment below to create an instance of WorkQueue
            //instance = new WorkQueue();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkQueue
        /// </summary>
        [Fact]
        public void WorkQueueInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkQueue
            //Assert.IsType<WorkQueue>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IsPaused'
        /// </summary>
        [Fact]
        public void IsPausedTest()
        {
            // TODO unit test for the property 'IsPaused'
        }

        /// <summary>
        /// Test the property 'ConcurrencyLimit'
        /// </summary>
        [Fact]
        public void ConcurrencyLimitTest()
        {
            // TODO unit test for the property 'ConcurrencyLimit'
        }

        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Fact]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }

        /// <summary>
        /// Test the property 'WorkPoolId'
        /// </summary>
        [Fact]
        public void WorkPoolIdTest()
        {
            // TODO unit test for the property 'WorkPoolId'
        }

        /// <summary>
        /// Test the property 'Filter'
        /// </summary>
        [Fact]
        public void FilterTest()
        {
            // TODO unit test for the property 'Filter'
        }

        /// <summary>
        /// Test the property 'LastPolled'
        /// </summary>
        [Fact]
        public void LastPolledTest()
        {
            // TODO unit test for the property 'LastPolled'
        }
    }
}
