/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using PrefectClient.Model;
using PrefectClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace PrefectClient.Test.Model
{
    /// <summary>
    ///  Class for testing WorkPool
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkPoolTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkPool
        //private WorkPool instance;

        public WorkPoolTests()
        {
            // TODO uncomment below to create an instance of WorkPool
            //instance = new WorkPool();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkPool
        /// </summary>
        [Fact]
        public void WorkPoolInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkPool
            //Assert.IsType<WorkPool>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Updated'
        /// </summary>
        [Fact]
        public void UpdatedTest()
        {
            // TODO unit test for the property 'Updated'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'BaseJobTemplate'
        /// </summary>
        [Fact]
        public void BaseJobTemplateTest()
        {
            // TODO unit test for the property 'BaseJobTemplate'
        }

        /// <summary>
        /// Test the property 'IsPaused'
        /// </summary>
        [Fact]
        public void IsPausedTest()
        {
            // TODO unit test for the property 'IsPaused'
        }

        /// <summary>
        /// Test the property 'ConcurrencyLimit'
        /// </summary>
        [Fact]
        public void ConcurrencyLimitTest()
        {
            // TODO unit test for the property 'ConcurrencyLimit'
        }

        /// <summary>
        /// Test the property 'DefaultQueueId'
        /// </summary>
        [Fact]
        public void DefaultQueueIdTest()
        {
            // TODO unit test for the property 'DefaultQueueId'
        }
    }
}
