/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using PrefectClient.Client;
using PrefectClient.Api;
// uncomment below to import models
//using PrefectClient.Model;

namespace PrefectClient.Test.Api
{
    /// <summary>
    ///  Class for testing FlowRunStatesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FlowRunStatesApiTests : IDisposable
    {
        private FlowRunStatesApi instance;

        public FlowRunStatesApiTests()
        {
            instance = new FlowRunStatesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FlowRunStatesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FlowRunStatesApi
            //Assert.IsType<FlowRunStatesApi>(instance);
        }

        /// <summary>
        /// Test ReadFlowRunState
        /// </summary>
        [Fact]
        public void ReadFlowRunStateTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.ReadFlowRunState(id);
            //Assert.IsType<State>(response);
        }

        /// <summary>
        /// Test ReadFlowRunStates
        /// </summary>
        [Fact]
        public void ReadFlowRunStatesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid flowRunId = null;
            //var response = instance.ReadFlowRunStates(flowRunId);
            //Assert.IsType<List<State>>(response);
        }
    }
}
