/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PrefectClient.Client.FileParameter;
using OpenAPIDateConverter = PrefectClient.Client.OpenAPIDateConverter;

namespace PrefectClient.Model
{
    /// <summary>
    /// Filter by `BlockDocument.is_anonymous`.
    /// </summary>
    [DataContract(Name = "BlockDocumentFilterIsAnonymous")]
    public partial class BlockDocumentFilterIsAnonymous : IEquatable<BlockDocumentFilterIsAnonymous>, IValidatableObject
    {
                

        /// <summary>
        /// Filter block documents for only those that are or are not anonymous.
        /// </summary>
        /// <value>Filter block documents for only those that are or are not anonymous.</value>
        [DataMember(Name = "eq_", EmitDefaultValue = true)]
        public bool? Eq { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BlockDocumentFilterIsAnonymous {\n");
            sb.Append("  Eq: ").Append(Eq).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BlockDocumentFilterIsAnonymous);
        }

        /// <summary>
        /// Returns true if BlockDocumentFilterIsAnonymous instances are equal
        /// </summary>
        /// <param name="input">Instance of BlockDocumentFilterIsAnonymous to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BlockDocumentFilterIsAnonymous input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Eq == input.Eq ||
                    this.Eq.Equals(input.Eq)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Eq.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
