/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PrefectClient.Client.FileParameter;
using OpenAPIDateConverter = PrefectClient.Client.OpenAPIDateConverter;

namespace PrefectClient.Model
{
    /// <summary>
    /// An ORM representation of a concurrency limit.
    /// </summary>
    [DataContract(Name = "ConcurrencyLimit")]
    public partial class ConcurrencyLimit : IEquatable<ConcurrencyLimit>, IValidatableObject
    {
                /// <summary>
        /// Initializes a new instance of the <see cref="ConcurrencyLimit" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ConcurrencyLimit() { }
        

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name = "created", EmitDefaultValue = false)]
        public DateTime? Created { get; set; }

        /// <summary>
        /// Gets or Sets Updated
        /// </summary>
        [DataMember(Name = "updated", EmitDefaultValue = false)]
        public DateTime? Updated { get; set; }

        /// <summary>
        /// A tag the concurrency limit is applied to.
        /// </summary>
        /// <value>A tag the concurrency limit is applied to.</value>
        [DataMember(Name = "tag", IsRequired = true, EmitDefaultValue = true)]
        public string? Tag { get; set; }

        /// <summary>
        /// The concurrency limit.
        /// </summary>
        /// <value>The concurrency limit.</value>
        [DataMember(Name = "concurrency_limit", IsRequired = true, EmitDefaultValue = true)]
        public int? VarConcurrencyLimit { get; set; }

        /// <summary>
        /// A list of active run ids using a concurrency slot
        /// </summary>
        /// <value>A list of active run ids using a concurrency slot</value>
        [DataMember(Name = "active_slots", EmitDefaultValue = false)]
        public List<Guid>? ActiveSlots { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ConcurrencyLimit {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Updated: ").Append(Updated).Append("\n");
            sb.Append("  Tag: ").Append(Tag).Append("\n");
            sb.Append("  VarConcurrencyLimit: ").Append(VarConcurrencyLimit).Append("\n");
            sb.Append("  ActiveSlots: ").Append(ActiveSlots).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ConcurrencyLimit);
        }

        /// <summary>
        /// Returns true if ConcurrencyLimit instances are equal
        /// </summary>
        /// <param name="input">Instance of ConcurrencyLimit to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConcurrencyLimit input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Created == input.Created ||
                    (this.Created != null &&
                    this.Created.Equals(input.Created))
                ) && 
                (
                    this.Updated == input.Updated ||
                    (this.Updated != null &&
                    this.Updated.Equals(input.Updated))
                ) && 
                (
                    this.Tag == input.Tag ||
                    (this.Tag != null &&
                    this.Tag.Equals(input.Tag))
                ) && 
                (
                    this.VarConcurrencyLimit == input.VarConcurrencyLimit ||
                    this.VarConcurrencyLimit.Equals(input.VarConcurrencyLimit)
                ) && 
                (
                    this.ActiveSlots == input.ActiveSlots ||
                    this.ActiveSlots != null &&
                    input.ActiveSlots != null &&
                    this.ActiveSlots.SequenceEqual(input.ActiveSlots)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.Created != null)
                {
                    hashCode = (hashCode * 59) + this.Created.GetHashCode();
                }
                if (this.Updated != null)
                {
                    hashCode = (hashCode * 59) + this.Updated.GetHashCode();
                }
                if (this.Tag != null)
                {
                    hashCode = (hashCode * 59) + this.Tag.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.VarConcurrencyLimit.GetHashCode();
                if (this.ActiveSlots != null)
                {
                    hashCode = (hashCode * 59) + this.ActiveSlots.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
