/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PrefectClient.Client.FileParameter;
using OpenAPIDateConverter = PrefectClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace PrefectClient.Model
{
    /// <summary>
    /// PrefectTaskDefaultRetryDelaySeconds
    /// </summary>
    [JsonConverter(typeof(PrefectTaskDefaultRetryDelaySecondsJsonConverter))]
    [DataContract(Name = "Prefect_Task_Default_Retry_Delay_Seconds")]
    public partial class PrefectTaskDefaultRetryDelaySeconds : AbstractOpenAPISchema, IEquatable<PrefectTaskDefaultRetryDelaySeconds>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PrefectTaskDefaultRetryDelaySeconds" /> class
        /// with the <see cref="decimal" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of decimal.</param>
        public PrefectTaskDefaultRetryDelaySeconds(decimal actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrefectTaskDefaultRetryDelaySeconds" /> class
        /// with the <see cref="int" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of int.</param>
        public PrefectTaskDefaultRetryDelaySeconds(int actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PrefectTaskDefaultRetryDelaySeconds" /> class
        /// with the <see cref="List{decimal}" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of List&lt;decimal&gt;.</param>
        public PrefectTaskDefaultRetryDelaySeconds(List<decimal> actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(List<decimal>))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(decimal))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(int))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: List<decimal>, decimal, int");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `decimal`. If the actual instance is not `decimal`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of decimal</returns>
        public decimal? GetDecimal()
        {
            return (decimal)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `int`. If the actual instance is not `int`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of int</returns>
        public int? GetInt()
        {
            return (int)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `List&lt;decimal&gt;`. If the actual instance is not `List&lt;decimal&gt;`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of List&lt;decimal&gt;</returns>
        public List<decimal>? GetList()
        {
            return (List<decimal>)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PrefectTaskDefaultRetryDelaySeconds {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, PrefectTaskDefaultRetryDelaySeconds.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of PrefectTaskDefaultRetryDelaySeconds
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of PrefectTaskDefaultRetryDelaySeconds</returns>
        public static PrefectTaskDefaultRetryDelaySeconds FromJson(string jsonString)
        {
            PrefectTaskDefaultRetryDelaySeconds newPrefectTaskDefaultRetryDelaySeconds = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newPrefectTaskDefaultRetryDelaySeconds;
            }

            try
            {
                newPrefectTaskDefaultRetryDelaySeconds = new PrefectTaskDefaultRetryDelaySeconds(JsonConvert.DeserializeObject<List<decimal>>(jsonString, PrefectTaskDefaultRetryDelaySeconds.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPrefectTaskDefaultRetryDelaySeconds;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into List<decimal>: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newPrefectTaskDefaultRetryDelaySeconds = new PrefectTaskDefaultRetryDelaySeconds(JsonConvert.DeserializeObject<decimal>(jsonString, PrefectTaskDefaultRetryDelaySeconds.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPrefectTaskDefaultRetryDelaySeconds;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into decimal: {1}", jsonString, exception.ToString()));
            }

            try
            {
                newPrefectTaskDefaultRetryDelaySeconds = new PrefectTaskDefaultRetryDelaySeconds(JsonConvert.DeserializeObject<int>(jsonString, PrefectTaskDefaultRetryDelaySeconds.SerializerSettings));
                // deserialization is considered successful at this point if no exception has been thrown.
                return newPrefectTaskDefaultRetryDelaySeconds;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into int: {1}", jsonString, exception.ToString()));
            }

            // no match found, throw an exception
            throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PrefectTaskDefaultRetryDelaySeconds);
        }

        /// <summary>
        /// Returns true if PrefectTaskDefaultRetryDelaySeconds instances are equal
        /// </summary>
        /// <param name="input">Instance of PrefectTaskDefaultRetryDelaySeconds to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PrefectTaskDefaultRetryDelaySeconds input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for PrefectTaskDefaultRetryDelaySeconds
    /// </summary>
    public class PrefectTaskDefaultRetryDelaySecondsJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(PrefectTaskDefaultRetryDelaySeconds).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return PrefectTaskDefaultRetryDelaySeconds.FromJson(JToken.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
