/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PrefectClient.Client.FileParameter;
using OpenAPIDateConverter = PrefectClient.Client.OpenAPIDateConverter;

namespace PrefectClient.Model
{
    /// <summary>
    /// ReadFlowRunNotificationPoliciesRequest
    /// </summary>
    [DataContract(Name = "ReadFlowRunNotificationPoliciesRequest")]
    public partial class ReadFlowRunNotificationPoliciesRequest : IEquatable<ReadFlowRunNotificationPoliciesRequest>, IValidatableObject
    {
                

        /// <summary>
        /// Gets or Sets FlowRunNotificationPolicyFilter
        /// </summary>
        [DataMember(Name = "flow_run_notification_policy_filter", EmitDefaultValue = false)]
        public FlowRunNotificationPolicyFilter FlowRunNotificationPolicyFilter { get; set; }

        /// <summary>
        /// Gets or Sets Offset
        /// </summary>
        [DataMember(Name = "offset", EmitDefaultValue = false)]
        public int? Offset { get; set; }

        /// <summary>
        /// Defaults to PREFECT_API_DEFAULT_LIMIT if not provided.
        /// </summary>
        /// <value>Defaults to PREFECT_API_DEFAULT_LIMIT if not provided.</value>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public int? Limit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReadFlowRunNotificationPoliciesRequest {\n");
            sb.Append("  FlowRunNotificationPolicyFilter: ").Append(FlowRunNotificationPolicyFilter).Append("\n");
            sb.Append("  Offset: ").Append(Offset).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReadFlowRunNotificationPoliciesRequest);
        }

        /// <summary>
        /// Returns true if ReadFlowRunNotificationPoliciesRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ReadFlowRunNotificationPoliciesRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReadFlowRunNotificationPoliciesRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.FlowRunNotificationPolicyFilter == input.FlowRunNotificationPolicyFilter ||
                    (this.FlowRunNotificationPolicyFilter != null &&
                    this.FlowRunNotificationPolicyFilter.Equals(input.FlowRunNotificationPolicyFilter))
                ) && 
                (
                    this.Offset == input.Offset ||
                    this.Offset.Equals(input.Offset)
                ) && 
                (
                    this.Limit == input.Limit ||
                    this.Limit.Equals(input.Limit)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FlowRunNotificationPolicyFilter != null)
                {
                    hashCode = (hashCode * 59) + this.FlowRunNotificationPolicyFilter.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Offset.GetHashCode();
                hashCode = (hashCode * 59) + this.Limit.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Offset (int) minimum
            if (this.Offset < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Offset, must be a value greater than or equal to 0.", new [] { "Offset" });
            }

            yield break;
        }
    }

}
