/*
 * Prefect API Client for .NET
 *
 * For more information, visit: https://github.com/rpeden/prefect-client-dotnet
 *
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = PrefectClient.Client.FileParameter;
using OpenAPIDateConverter = PrefectClient.Client.OpenAPIDateConverter;

namespace PrefectClient.Model
{
    /// <summary>
    /// Filter by `WorkQueue.name`.
    /// </summary>
    [DataContract(Name = "WorkQueueFilterName")]
    public partial class WorkQueueFilterName : IEquatable<WorkQueueFilterName>, IValidatableObject
    {
                

        /// <summary>
        /// A list of work queue names to include
        /// </summary>
        /// <value>A list of work queue names to include</value>
        /// <example>["wq-1","wq-2"]</example>
        [DataMember(Name = "any_", EmitDefaultValue = false)]
        public List<string>? Any { get; set; }

        /// <summary>
        /// A list of case-insensitive starts-with matches. For example,  passing 'marvin' will match 'marvin', and 'Marvin-robot', but not 'sad-marvin'.
        /// </summary>
        /// <value>A list of case-insensitive starts-with matches. For example,  passing &#39;marvin&#39; will match &#39;marvin&#39;, and &#39;Marvin-robot&#39;, but not &#39;sad-marvin&#39;.</value>
        /// <example>["marvin","Marvin-robot"]</example>
        [DataMember(Name = "startswith_", EmitDefaultValue = false)]
        public List<string>? Startswith { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WorkQueueFilterName {\n");
            sb.Append("  Any: ").Append(Any).Append("\n");
            sb.Append("  Startswith: ").Append(Startswith).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as WorkQueueFilterName);
        }

        /// <summary>
        /// Returns true if WorkQueueFilterName instances are equal
        /// </summary>
        /// <param name="input">Instance of WorkQueueFilterName to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(WorkQueueFilterName input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Any == input.Any ||
                    this.Any != null &&
                    input.Any != null &&
                    this.Any.SequenceEqual(input.Any)
                ) && 
                (
                    this.Startswith == input.Startswith ||
                    this.Startswith != null &&
                    input.Startswith != null &&
                    this.Startswith.SequenceEqual(input.Startswith)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Any != null)
                {
                    hashCode = (hashCode * 59) + this.Any.GetHashCode();
                }
                if (this.Startswith != null)
                {
                    hashCode = (hashCode * 59) + this.Startswith.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
